### PR TITLE
issues #9 

### PR DESCRIPTION
**Pull request by jparadasb**
Rescued parser error when the api does not respond or responds with html

### CODE REVIEW

**Comment by eddwinpaz** [comment]
This issue has been addressed, Can you explain how you may cause this error please.

**Comment by GusGA** [comment]
To close successfully the pull request, this commit must be accompanied by test which capture the exception if this becomes

**Comment by highercomve** [comment]
I think, is not better to validate the response to be a json and if is not a json, return a json error. Because el JSON.parse is exploding and you only are catching that error, but in some scenarios this JSON.parse exception could by catch by another piece of software and crash. Example: sidekiq will catch that exception and retry to send another message until 25 retires (by default).

Always is better to be safe that this is not gonna thrown an exception, and if the API response an unexpected format, convert that in a correct format (JSON).

**Comment by eddwinpaz** [comment]
We will make better json improvements in our new API.

**Pull request closed without merging**
